select * from INFORMATION_SCHEMA.CHECK_CONSTRAINTS
select * from INFORMATION_SCHEMA.COLUMN_DOMAIN_USAGE ORDER BY DOMAIN_SCHEMA, DOMAIN_NAME, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
select * from INFORMATION_SCHEMA.COLUMN_PRIVILEGES ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
select * from INFORMATION_SCHEMA.COLUMNS ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ORDER BY TABLE_SCHEMA, TABLE_NAME
select * from INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE ORDER BY TABLE_SCHEMA, TABLE_NAME
select * from INFORMATION_SCHEMA.DOMAIN_CONSTRAINTS
select * from INFORMATION_SCHEMA.DOMAINS ORDER BY DOMAIN_SCHEMA, DOMAIN_NAME
select * from INFORMATION_SCHEMA.KEY_COLUMN_USAGE ORDER BY TABLE_SCHEMA, TABLE_NAME, CONSTRAINT_NAME, ORDINAL_POSITION
select * from INFORMATION_SCHEMA.PARAMETERS ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ORDINAL_POSITION
select * from INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS ORDER BY CONSTRAINT_SCHEMA, CONSTRAINT_NAME
select * from INFORMATION_SCHEMA.ROUTINES ORDER BY SPECIFIC_SCHEMA, SPECIFIC_NAME
select * from INFORMATION_SCHEMA.ROUTINE_COLUMNS
select * from INFORMATION_SCHEMA.SCHEMATA ORDER BY CATALOG_NAME, SCHEMA_NAME
select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS ORDER BY TABLE_SCHEMA, TABLE_NAME, CONSTRAINT_NAME
select * from INFORMATION_SCHEMA.TABLE_PRIVILEGES
select * from INFORMATION_SCHEMA.TABLES ORDER BY TABLE_SCHEMA, TABLE_TYPE, TABLE_NAME
select * from INFORMATION_SCHEMA.VIEW_COLUMN_USAGE ORDER BY VIEW_SCHEMA, VIEW_NAME, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
select * from INFORMATION_SCHEMA.VIEW_TABLE_USAGE ORDER BY VIEW_SCHEMA, VIEW_NAME, TABLE_SCHEMA, TABLE_NAME
select * from INFORMATION_SCHEMA.VIEWS ORDER BY TABLE_SCHEMA, TABLE_NAME


